export default [
    {
        postId:1,
        userEmail:"chowdhuryittehad@gmail.com",
        userContact:"01712345678",
        title : "Dorm 1",
        rent : 1000,
        mapLink : "Location 1",
        address:{
            house: "House 1",
            street:"Street 1",
            city:"City 1",
        },
        images :{
            imagePath1:"./publicImage/image1.jpg",
            imagePath2:"./publicImage/image2.jpg",
            imagePath3:"./publicImage/image3.jpg",
        },
        windowCount : 4,
        isToiletAttached : true,
        isKitchenAvailable : true,
        dimensions:{
            length:10,
            width:15,
        },
        vacancy : 1,
        capacity : 2,
        keyFeatures : "Good place",
        description : "IDK Dorm Good",
        prefGender : "male",
    },
    {
        postID : 2,
        userEmail:"chowdhuryittehad@gmail.com",
        userContact:"01712345678",
        title : "Dorm 2",
        rent : 2000,
        mapLink : "Location 2",
        address:{
            house: "House 2",
            street:"Street 2",
            city:"City 2",
        },
        images :{
            imagePath1:"./publicImage/image2.jpg",
            imagePath2:"./publicImage/image1.jpg",
            imagePath3:"./publicImage/image3.jpg",
        },
        windowCount : 4,
        isToiletAttached : false,
        isKitchenAvailable : true,
        dimensions:{
            length:10,
            width:15,
        },
        vacancy : 1,
        capacity : 2,
        keyFeatures : "Good place",
        description : "IDK Dorm Good",
        prefGender : "female",
    },
    {
        postID : 3,
        userEmail:"doctorstrange988@gmail.com",
        title : "Dorm 3",
        rent : 3000,
        mapLink : "Location 3",
        address:{
            house: "House 3",
            street:"Street 3",
            city:"City 3",
        },
        images :{
            imagePath1:"./publicImage/image3.jpg",
            imagePath2:"./publicImage/image2.jpg",
            imagePath3:"./publicImage/image1.jpg",
        },
        windowCount : 4,
        isToiletAttached : true,
        isKitchenAvailable :false,
        dimensions:{
            length:10,
            width:15,
        },
        vacancy : 1,
        capacity : 2,
        keyFeatures : "Good place",
        description : "IDK Dorm Good",
        prefGender : "female",
    }
]